keys:
  grz_public_key_path: 'grz-inbox.pub'
  grz_private_key_path: 'grz-inbox.sec'
s3:
  endpoint_url: "http://s3service:9000"
  access_key_id: "Gd4G0VqhHTmi28twgsmF"
  secret_access_key: "KEx8ABzui36NhyXbiQwYXxps3HahqD7EKL54v65f"
  bucket: inbox-le-2