channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - snakemake =9.1.1
  - snakefmt
  - snakemake-storage-plugin-s3
  - snakemake-executor-plugin-slurm
  - snakemake-executor-plugin-kubernetes
  - filelock =3.18.0
  - uv =0.6.9

