monitor:
  active: false
  state_file: "state/metadata.jsonl"
  interval: 3600 # in seconds

grz_inbox:
  public_key: "grz_inbox_public_key"
  s3_config:
    endpoint_url: "https://foo.bar"
    access_key_id: "access_key_id"
    secret_access_key: "secret_access_key"
    buckets:
      - A
      - B

grz_internal:
  public_key: "grz_internal_public_key"
  s3_config:
    endpoint_url: "https://foo.bar"
    access_key_id: "access_key_id"
    secret_access_key: "secret_access_key"
    buckets:
      - archive

ghga:
  public_key: "ghga_public_key"
  s3_config:
    endpoint_url: "https://foo.bar"
    access_key_id: "access_key_id"
    secret_access_key: "secret_access_key"
    buckets:
      - inbox