monitor:
  submission_db: "sqlite:///state/metadata.sqlite"
  interval: 10 # in seconds

buckets:
  inbox:
    inbox-le-1: "config/buckets/inbox-le-1.config.yaml"
    inbox-le-2: "config/buckets/inbox-le-2.config.yaml"
  consented: "config/buckets/consented.yaml"
  nonconsented: "config/buckets/nonconsented.yaml"
